export const env = {
    POKE_API_URL: process.env.REACT_APP_POKE_API_URL,
    POKEDEX_API_URL: process.env.REACT_APP_POKEDEX_API_URL,
    POKEMON_IMAGES: process.env.REACT_APP_POKEMON_IMAGES,
    POKEMON_IMAGES_GIF: process.env.REACT_APP_POKEMON_IMAGES_GIF,
    POKEMON_SHINY_IMAGES: process.env.REACT_APP_POKEMON_SHINY_IMAGES,
    NUMBER_POKEMONS: process.env.REACT_APP_MAX_NUMBER_POKEMONS,
    NUMBER_GENERATE_POKEMONS: process.env.REACT_APP_MAX_NUMBER_GENERATE_POKEMONS,
};
