import {
    Bug,
    Dark,
    Dragon,
    Electric,
    Fairy,
    Female,
    FemaleShiny,
    Fighting,
    Fire,
    Flying,
    Ghost,
    Grass,
    Ground,
    Ice,
    Male,
    MaleShiny,
    Normal,
    Poison,
    Psychic,
    Rock,
    Steel,
    Water,
} from '../assets/images';

export const POKEMON_TYPES = {
    bug: Bug,
    dark: Dark,
    dragon: Dragon,
    electric: Electric,
    fairy: Fairy,
    fighting: Fighting,
    fire: Fire,
    flying: Flying,
    ghost: Ghost,
    grass: Grass,
    ground: Ground,
    ice: Ice,
    normal: Normal,
    poison: Poison,
    psychic: Psychic,
    rock: Rock,
    steel: Steel,
    water: Water,
};

export const POKEMON_GENDER = {
    female: Female,
    male: Male,
    female_shiny: FemaleShiny,
    male_shiny: MaleShiny,
};
